# Generated by Django 3.1.1 on 2020-12-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateproduct',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='An un labeled product', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='summery',
            field=models.TextField(default='Hello'),
        ),
    ]
